eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

resilience4j:
  ratelimiter:
    instances:
      productRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 1s
      cartRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 1s
      wishlistRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 1s