apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: tripezzy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: rupaldraft/tripezzy-backend-admin-service
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: admin-service-secret
