spring.application.name: ${SPRING_APPLICATION_NAME}
eureka.client.service-url.defaultZone: ${EUREKA_SERVER_URL}
server.port: ${SERVER_PORT}

jwt:
  secretKey: ${JWT_SECRET_KEY}


spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: eCommerce-service
          uri: lb://ECOMMERCE-SERVICE
          predicates:
            - Path=/api/v1/shop/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: blog-service
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/api/v1/blogs/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
