apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: notification-db
spec:
  ports:
    - port: 5432
  selector:
    app: notification-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-db
spec:
  selector:
    matchLabels:
      app: notification-db
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
        - name: notification-db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: notificationDB
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: tulshi paul
          volumeMounts:
            - name: notification-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: notification-db-storage
          persistentVolumeClaim:
            claimName: notification-db-pvc
