eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

resilience4j:
  ratelimiter:
    instances:
      checkoutProducts:
        limitForPeriod: 5
        limitRefreshPeriod: 5m
        timeoutDuration: 1s
      checkoutBookings:
        limitForPeriod: 5
        limitRefreshPeriod: 5m
        timeoutDuration: 1s
      paymentsRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 5m
        timeoutDuration: 1s
      userPaymentsRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 5m
        timeoutDuration: 1s