apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: tripezzy
spec:
  selector:
    app: booking-service
  ports:
    - name: http
      port: 80
      targetPort: 9010
    - name: grpc
      port: 9011
      targetPort: 9011
