apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: tripezzy
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 80
      targetPort: 7000
    - name: grpc
      port: 7001
      targetPort: 7001
