apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: tripezzy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
        - name: blog-service
          image: rupaldraft/tripezzy-backend-blog-service
          ports:
            - containerPort: 9000  # HTTP port
            - containerPort: 9001  # gRPC port
          envFrom:
            - secretRef:
                name: blog-service-secret
