apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: tripezzy
spec:
  selector:
    app: blog-service
  ports:
    - name: http
      port: 80
      targetPort: 9000
    - name: grpc
      port: 9001
      targetPort: 9001
