apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: tripezzy
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 80
      targetPort: 4000
    - name: grpc
      port: 4001
      targetPort: 4001
