apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: tripezzy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: rupaldraft/tripezzy-backend-payment-service
          ports:
            - containerPort: 4000  # HTTP
            - containerPort: 4001  # gRPC
          envFrom:
            - secretRef:
                name: payment-service-secret
