apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: tripezzy
spec:
  selector:
    app: ecommerce-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: grpc
      port: 8001
      targetPort: 8001
