apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: tripezzy
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 80
      targetPort: 6000
    - name: grpc
      port: 6001
      targetPort: 6001
